/* Copyright (c) 2026 BuildCraft team
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
 * distributed with this file, You can obtain one at https://mozilla.org/MPL/2.0/. */

package buildcraft.datagen;

import java.util.Map;

/**
 * M3.4: the frozen 857-key English lang table, in committed key order. This is the M3.5 mechanical copy of the
 * BuildCraft-Localization {@code en_us.json} master file (see tasks.json M3.5); it is embedded here so
 * {@link BcLangProvider} REBUILDS {@code assets/buildcraftcore/lang/en_us.json} from code — any hand edit of the
 * shipped file shows up as a drift in the M3.4 runData diff gate instead of passing silently.
 *
 * <p>Generated helper; do not hand-edit the table (regenerate it from the committed lang file instead).
 */
public final class BcLangData {

    private BcLangData() {
    }

    /** Frozen key count, asserted by the provider wiring. */
    public static final int KEY_COUNT = 857;

    /** Adds all 857 entries to {@code map} in committed order. */
    public static void addTo(Map<String, String> map) {
        map.put("buildcraft.boardRobotClean", "Clean");
        map.put("buildcraft.boardRobotPicker", "Picker");
        map.put("buildcraft.boardRobotLumberjack", "Lumberjack");
        map.put("buildcraft.boardRobotPlanter", "Planter");
        map.put("buildcraft.boardRobotLeaveCutter", "Leaf Cutter");
        map.put("buildcraft.boardRobotCarrier", "Carrier");
        map.put("buildcraft.boardRobotFluidCarrier", "Tank");
        map.put("buildcraft.boardRobotBomber", "Bomber");
        map.put("buildcraft.boardRobotKnight", "Knight");
        map.put("buildcraft.boardRobotMiner", "Miner");
        map.put("buildcraft.boardRobotFarmer", "Farmer");
        map.put("buildcraft.boardRobotHarvester", "Harvester");
        map.put("buildcraft.boardRobotShovelman", "Shovelman");
        map.put("buildcraft.boardRobotButcher", "Butcher");
        map.put("buildcraft.boardRobotBuilder", "Builder");
        map.put("buildcraft.boardRobotCrafter", "Crafter");
        map.put("buildcraft.boardRobotDelivery", "Delivery");
        map.put("buildcraft.boardRobotPump", "Pump");
        map.put("buildcraft.boardRobotStripes", "Stripes");
        map.put("buildcraft.boardRobotBreaker", "Breaker");
        map.put("buildcraft.boardRobotPicker.desc", "Picks up items");
        map.put("buildcraft.boardRobotLumberjack.desc", "Breaks logs");
        map.put("buildcraft.boardRobotPlanter.desc", "Plants crops");
        map.put("buildcraft.boardRobotLeaveCutter.desc", "Cuts leaves");
        map.put("buildcraft.boardRobotCarrier.desc", "Moves items between inventories");
        map.put("buildcraft.boardRobotFluidCarrier.desc", "Moves fluids between tanks");
        map.put("buildcraft.boardRobotBomber.desc", "Bombs locations");
        map.put("buildcraft.boardRobotKnight.desc", "Fights mobs");
        map.put("buildcraft.boardRobotMiner.desc", "Mines ores");
        map.put("buildcraft.boardRobotFarmer.desc", "Hoes dirt");
        map.put("buildcraft.boardRobotHarvester.desc", "Harvests mature crops");
        map.put("buildcraft.boardRobotShovelman.desc", "Shovels area");
        map.put("buildcraft.boardRobotButcher.desc", "Fights animals");
        map.put("buildcraft.boardRobotBuilder.desc", "Builds structures");
        map.put("buildcraft.boardRobotCrafter.desc", "Crafts items");
        map.put("buildcraft.boardRobotDelivery.desc", "Delivers items upon request");
        map.put("buildcraft.boardRobotPump.desc", "Pumps out liquids");
        map.put("buildcraft.boardRobotStripes.desc", "Uhh... Stripes!");
        map.put("buildcraft.boardRobotBreaker.desc", "Mines stone");
        map.put("chat.gateCopier.clear", "Gate information cleared.");
        map.put("chat.gateCopier.gateCopied", "Copied gate information to copier.");
        map.put("chat.gateCopier.gatePasted", "Pasted copied data to gate.");
        map.put("chat.gateCopier.noGate", "No gate found on this side!");
        map.put("chat.gateCopier.noInformation", "No gate information stored!");
        map.put("chat.gateCopier.warning.actionParameters", "\u00a76Warning: Target has less action parameters!");
        map.put("chat.gateCopier.warning.logic", "\u00a76Warning: Target has different logic type!");
        map.put("chat.gateCopier.warning.load", "\u00a76Warning: Gate triggers/actions might be missing!");
        map.put("chat.gateCopier.warning.slots", "\u00a76Warning: Target has less slots!");
        map.put("chat.gateCopier.warning.triggerParameters", "\u00a76Warning: Target has less trigger parameters!");
        map.put("chat.pipe.power.iron.mode", "Switched to %d MJ/t limit");
        map.put("gate.action.pipe.power_limit", "Switch to %d MJ/t limit");
        map.put("chat.pipe.rf.iron.mode", "Switched to %d RF/t limit");
        map.put("gate.action.pipe.rf_limit", "Switch to %d RF/t limit");
        map.put("chat.pipe.power.iron.mode.numberless", "Switched to %s limit");
        map.put("chat.pipe.power.iron.level.20", "Very Low");
        map.put("chat.pipe.power.iron.level.40", "Low");
        map.put("chat.pipe.power.iron.level.80", "Medium-Low");
        map.put("chat.pipe.power.iron.level.160", "Medium");
        map.put("chat.pipe.power.iron.level.320", "Medium-High");
        map.put("chat.pipe.power.iron.level.640", "High");
        map.put("chat.pipe.power.iron.level.1280", "Very High");
        map.put("chat.pipe.power.iron.level.2560", "Full Capacity");
        map.put("color.clear", "Clear");
        map.put("color.black", "Black");
        map.put("color.blue", "Blue");
        map.put("color.brown", "Brown");
        map.put("color.cyan", "Cyan");
        map.put("color.gray", "Gray");
        map.put("color.green", "Green");
        map.put("color.light.blue", "Light Blue");
        map.put("color.light.gray", "Light Gray");
        map.put("color.lime", "Lime");
        map.put("color.magenta", "Magenta");
        map.put("color.orange", "Orange");
        map.put("color.pink", "Pink");
        map.put("color.purple", "Purple");
        map.put("color.red", "Red");
        map.put("color.white", "White");
        map.put("color.yellow", "Yellow");
        map.put("config.general", "General");
        map.put("config.general.pipes", "Pipes");
        map.put("config.blueprints", "Blueprints");
        map.put("config.builders", "Builders");
        map.put("config.power", "Power Usage");
        map.put("config.experimental", "Experimental");
        map.put("config.display", "Display");
        map.put("config.performance", "Performance");
        map.put("config.worldgen", "World Generation");
        map.put("config.network", "Networking");
        map.put("config.buildcraft", "BuildCraft Configuration");
        map.put("config.blueprints.clientDatabaseDirectory", "Client directory");
        map.put("config.blueprints.excludedMods", "Excluded mods");
        map.put("config.blueprints.excludedBlocks", "Excluded blocks");
        map.put("config.builders.dropBrokenBlocks", "Drop broken blocks");
        map.put("config.display.colorBlindMode", "Colorblind mode");
        map.put("config.display.hideFluidValues", "Hide fluid numbers");
        map.put("config.display.hidePowerValues", "Hide power numbers");
        map.put("config.experimental.kinesisPowerLossOnTravel", "Kinesis pipes power perdition");
        map.put("config.general.boards.blacklist", "Robot blacklist");
        map.put("config.general.pumpsConsumeWater", "Pumps consume water");
        map.put("config.general.updateCheck", "Check for updates");
        map.put("config.general.fuel.fuel.combustion", "Combustion engine fuel multiplier");
        map.put("config.general.fuel.oil.combustion", "Combustion engine oil multiplier");
        map.put("config.general.fuel.fuel.combustion.energyOutput", "Combustion engine fuel output");
        map.put("config.general.fuel.oil.combustion.energyOutput", "Combustion engine oil output");
        map.put("config.general.itemLifespan", "Item lifespan (seconds)");
        map.put("config.general.canEnginesExplode", "Engines explode");
        map.put("config.general.oilCanBurn", "Burning oil");
        map.put("config.general.oilIsDense", "Dense oil");
        map.put("config.general.pipes.baseFluidRate", "Base flow rate");
        map.put("config.general.pipes.facadeBlacklist", "Facade blacklist");
        map.put("config.general.pipes.facadeBlacklistAsWhitelist", "Invert facade blacklist");
        map.put("config.general.pipes.facadeNoLaserRecipe", "Add facade recipe without laser");
        map.put("config.general.pipes.hardness", "Hardness");
        map.put("config.general.pipes.slimeballWaterproofRecipe", "Add slimeball sealant recipe");
        map.put("config.general.pumpsNeedRealPower", "Pumps need real power");
        map.put("config.general.quarry", "Quarry Options");
        map.put("config.general.quarry.oneTimeUse", "One-time use");
        map.put("config.general.quarry.doChunkLoading", "Automatic chunk loading");
        map.put("config.general.markerRange", "Range of markers");
        map.put("config.general.miningDepth", "Maximum relative mining depth");
        map.put("config.general.pumpDimensionControl", "Pump dimension control");
        map.put("config.network.longUpdateFactor", "Client synchronization factor (ticks)");
        map.put("config.network.updateFactor", "Packet sending factor (ticks)");
        map.put("config.power.miningUsageMultiplier", "Mining usage multiplier");
        map.put("config.power.chipsetCostMultiplier", "Chipset cost multiplier");
        map.put("config.power.gateCostMultiplier", "Gate cost multiplier");
        map.put("config.worldgen.enable", "Enable");
        map.put("config.worldgen.generateWaterSprings", "Spawn water springs");
        map.put("config.worldgen.oilWellGenerationRate", "Oil well generation rate");
        map.put("config.worldgen.spawnOilSprings", "Spawn oil springs");
        map.put("config.worldgen.biomes.biomeOilDesert", "Oil Desert biome id");
        map.put("config.worldgen.biomes.biomeOilOcean", "Oil Ocean biome id");
        map.put("config.worldgen.biomes.excessiveOilIDs", "Biomes with excessive oil");
        map.put("config.worldgen.biomes.excludeOilIDs", "Biomes without oil");
        map.put("config.worldgen.biomes.increasedOilIDs", "Biomes with increased oil");
        map.put("direction.north", "North");
        map.put("direction.west", "West");
        map.put("direction.east", "East");
        map.put("direction.south", "South");
        map.put("direction.up", "Top");
        map.put("direction.down", "Bottom");
        map.put("direction.center", "Center");
        map.put("direction.center.0", "North-West");
        map.put("direction.center.1", "North");
        map.put("direction.center.2", "North-East");
        map.put("direction.center.3", "West");
        map.put("direction.center.4", "Center");
        map.put("direction.center.5", "East");
        map.put("direction.center.6", "South-West");
        map.put("direction.center.7", "South");
        map.put("direction.center.8", "South-East");
        map.put("buildcraft.fluid.empty", "Empty");
        map.put("buildcraft.fluid.static.milli.short", "%s mB");
        map.put("buildcraft.fluid.static.bucket.short", "%s B");
        map.put("buildcraft.fluid.static.milli.long", "%s milli buckets");
        map.put("buildcraft.fluid.static.bucket.long", "%s buckets");
        map.put("buildcraft.fluid.empty.milli.short", "0 / %s mB");
        map.put("buildcraft.fluid.empty.bucket.short", "0 / %s B");
        map.put("buildcraft.fluid.empty.milli.long", "Empty %s milli bucket tank");
        map.put("buildcraft.fluid.empty.bucket.long", "Empty %s bucket tank");
        map.put("buildcraft.fluid.full.milli.short", "%1$s / %1$s mB");
        map.put("buildcraft.fluid.full.bucket.short", "%1$s / %1$s B");
        map.put("buildcraft.fluid.full.milli.long", "Full %s milli bucket tank");
        map.put("buildcraft.fluid.full.bucket.long", "Full %s bucket tank");
        map.put("buildcraft.fluid.static.cap.milli.short", "%s / %s mB");
        map.put("buildcraft.fluid.static.cap.bucket.short", "%s / %s B");
        map.put("buildcraft.fluid.static.cap.milli.long", "%s milli buckets in a %s milli bucket tank");
        map.put("buildcraft.fluid.static.cap.bucket.long", "%s buckets in a %s bucket tank");
        map.put("buildcraft.fluid.flow.milli.short", "%s mB/t");
        map.put("buildcraft.fluid.flow.bucket.short", "%s B/s");
        map.put("buildcraft.fluid.flow.milli.long", "%s milli buckets per tick");
        map.put("buildcraft.fluid.flow.bucket.long", "%s buckets per second");
        map.put("buildcraft.mj.static.long", "%s Minecraft Joules");
        map.put("buildcraft.mj.static.short", "%s MJ");
        map.put("buildcraft.mj.flow.long", "%s Minecraft Joules per tick");
        map.put("buildcraft.mj.flow.short", "%s MJ/t");
        map.put("buildcraft.mj.flow.seconds.long", "%s Minecraft Joules per second");
        map.put("buildcraft.mj.flow.seconds.short", "%s MJ/s");
        map.put("buildcraft.rf.static.long", "%s Redstone Flux");
        map.put("buildcraft.rf.static.short", "%s RF");
        map.put("buildcraft.rf.flow.long", "%s Redstone Flux per tick");
        map.put("buildcraft.rf.flow.short", "%s RF/t");
        map.put("buildcraft.rf.flow.seconds.long", "%s Redstone Flux per second");
        map.put("buildcraft.rf.flow.seconds.short", "%s RF/s");
        map.put("fillerpattern.clear", "Clear");
        map.put("fillerpattern.fill", "Fill");
        map.put("fillerpattern.flatten", "Flatten");
        map.put("fillerpattern.horizon", "Horizon");
        map.put("fillerpattern.pyramid", "Pyramid");
        map.put("fillerpattern.stairs", "Stairs");
        map.put("fillerpattern.box", "Box");
        map.put("fillerpattern.frame", "Frame");
        map.put("fillerpattern.none", "None");
        map.put("fillerpattern.sphere_eighth", "Eighth-Sphere");
        map.put("fillerpattern.sphere_quarter", "Quarter-sphere");
        map.put("fillerpattern.sphere_half", "Hemisphere");
        map.put("fillerpattern.sphere", "Sphere");
        map.put("fillerpattern.2d_arc", "Arc");
        map.put("fillerpattern.2d_semi_circle", "Semi-Circle");
        map.put("fillerpattern.2d_circle", "Circle");
        map.put("fillerpattern.2d_triangle", "Triangle");
        map.put("fillerpattern.2d_square", "Square");
        map.put("fillerpattern.2d_pentagon", "Pentagon");
        map.put("fillerpattern.2d_hexagon", "Hexagon");
        map.put("fillerpattern.2d_octagon", "Octagon");
        map.put("fillerpattern.parameter.hollow", "Hollow");
        map.put("fillerpattern.parameter.filled", "Filled");
        map.put("fillerpattern.parameter.filled_outer", "Surrounded");
        map.put("buildcraft.param.rotation.0", "No rotation");
        map.put("buildcraft.param.rotation.1", "90 degree rotation");
        map.put("buildcraft.param.rotation.2", "180 degree rotation");
        map.put("buildcraft.param.rotation.3", "270 degree rotation");
        map.put("buildcraft.param.axis.x", "X Axis");
        map.put("buildcraft.param.axis.y", "Y Axis");
        map.put("buildcraft.param.axis.z", "Z Axis");
        map.put("fluid.oil", "Oil");
        map.put("fluid.fuel", "Light Fuel");
        map.put("fluid.oil_distilled", "Distilled Oil");
        map.put("fluid.oil_heavy", "Heavy Oil");
        map.put("fluid.oil_dense", "Dense Oil");
        map.put("fluid.oil_residue", "Residue");
        map.put("fluid.tar", "Tar");
        map.put("fluid.fuel_mixed", "Mixed Fuels");
        map.put("fluid.fuel_mixed_heavy", "Mixed Heavy Fuels");
        map.put("fluid.fuel_mixed_light", "Mixed Light Fuels");
        map.put("fluid.fuel_dense", "Dense Fuel");
        map.put("fluid.fuel_light", "Light Fuel");
        map.put("fluid.fuel_gaseous", "Gaseous Fuel");
        map.put("buildcraft.fluid.heat_0", "%s (\u00a7bCool\u00a7r)");
        map.put("buildcraft.fluid.heat_1", "%s (\u00a76Hot\u00a7r)");
        map.put("buildcraft.fluid.heat_2", "%s (\u00a7cSearing\u00a7r)");
        map.put("buildcraft.christmas.fluid.oil", "Raw Chocolate Mix");
        map.put("buildcraft.christmas.fluid.fuel", "Milk Chocolate");
        map.put("buildcraft.christmas.fluid.oil_distilled", "Mixed Chocolates");
        map.put("buildcraft.christmas.fluid.oil_heavy", "Raw Chocolate");
        map.put("buildcraft.christmas.fluid.oil_dense", "Raw Heavy Chocolates");
        map.put("buildcraft.christmas.fluid.oil_residue", "Caramel Excess");
        map.put("buildcraft.christmas.fluid.fuel_mixed_heavy", "Darker Chocolate Mix");
        map.put("buildcraft.christmas.fluid.fuel_mixed_light", "Lighter Chocolate Mix");
        map.put("buildcraft.christmas.fluid.fuel_dense", "Dark Chocolate");
        map.put("buildcraft.christmas.fluid.fuel_light", "Milk Chocolate");
        map.put("buildcraft.christmas.fluid.fuel_gaseous", "White Chocolate");
        map.put("buildcraft.christmas.buildcraft.fluid.heat_0", "\u00a7bMelted\u00a7r %s");
        map.put("buildcraft.christmas.buildcraft.fluid.heat_1", "\u00a76Bubbling\u00a7r %s");
        map.put("buildcraft.christmas.buildcraft.fluid.heat_2", "\u00a7cSearing\u00a7r %s");
        map.put("buildcraft.christmas.tile.engineIron.name", "Chocolate Engine");
        map.put("gate.action.extraction", "%s Extraction Preset");
        map.put("gate.action.pipe.item.color", "Paint Items %s");
        map.put("gate.action.machine.on", "On");
        map.put("gate.action.machine.off", "Off");
        map.put("gate.action.machine.loop", "Loop");
        map.put("gate.action.pulsar.constant", "Power Pulsar");
        map.put("gate.action.pulsar.single", "Single Power Pulse");
        map.put("gate.action.pipe.wire", "%s Pipe Signal");
        map.put("gate.action.redstone.signal", "Redstone Signal");
        map.put("gate.action.robot.goto_station", "Goto Station");
        map.put("gate.action.pipe.valve.open", "Open");
        map.put("gate.action.pipe.valve.input_only", "Input Only");
        map.put("gate.action.pipe.valve.output_only", "Output Only");
        map.put("gate.action.pipe.valve.closed", "Closed");
        map.put("gate.action.station.provide_items", "Provide Items");
        map.put("gate.action.station.accept_items", "Accept Items");
        map.put("gate.action.station.request_items", "Request Items");
        map.put("gate.action.station.drop_items_in_pipe", "Drop Items In Pipe");
        map.put("gate.action.station.allow_craft", "Allow Craft");
        map.put("gate.action.station.provide_machine_request", "Request Needed Items");
        map.put("gate.action.station.accept_fluids", "Accept Fluids");
        map.put("gate.action.station.povide_fluids", "Provide Fluids");
        map.put("gate.action.robot.work_in_area", "Work in Area");
        map.put("gate.action.robot.load_unload_area", "Load/Unload in Area");
        map.put("gate.action.robot.wakeup", "Wake Up");
        map.put("gate.action.station.forbid_robot", "Forbid Robot");
        map.put("gate.action.station.force_robot", "Force Robot");
        map.put("gate.action.robot.filter", "Filter");
        map.put("gate.action.robot.filter_tool", "Filter Tool");
        map.put("gate.action.pipe.direction", "Face the %s side");
        map.put("gate.logic.and", "AND");
        map.put("gate.logic.or", "OR");
        map.put("gate.material.iron", "Iron");
        map.put("gate.material.nether_brick", "Nether Brick");
        map.put("gate.material.gold", "Gold");
        map.put("gate.slots", "%s Slots");
        map.put("gate.params", "%s Slot Parameters");
        map.put("gate.params.trigger", "%s Trigger Parameters");
        map.put("gate.params.action", "%s Action Parameters");
        map.put("gate.side", "\u00a77on the %s\u00a77 side");
        map.put("gate.name", "%s %s Gate");
        map.put("gate.name.basic", "Basic Gate");
        map.put("gate.parameter.redstone.gateSideOnly", "Gate Side Only");
        map.put("gate.trigger.true", "Always On");
        map.put("gate.trigger.engine.blue", "Engine Blue");
        map.put("gate.trigger.engine.green", "Engine Green");
        map.put("gate.trigger.engine.yellow", "Engine Yellow");
        map.put("gate.trigger.engine.red", "Engine Red");
        map.put("gate.trigger.engine.overheat", "Engine Overheat");
        map.put("gate.trigger.fluid.empty", "Tank Empty");
        map.put("gate.trigger.fluid.contains", "Fluid in Tank");
        map.put("gate.trigger.fluid.space", "Space for Fluid");
        map.put("gate.trigger.fluid.full", "Tank Full");
        map.put("gate.trigger.fluidlevel.below", "Contains < %d%%");
        map.put("gate.trigger.inventory.empty", "Inventory Empty");
        map.put("gate.trigger.inventory.contains", "Items in Inventory");
        map.put("gate.trigger.inventory.space", "Space in Inventory");
        map.put("gate.trigger.inventory.full", "Inventory Full");
        map.put("gate.trigger.inventorylevel.below", "Contains < %d%%");
        map.put("gate.trigger.machine.done", "Work Done");
        map.put("gate.trigger.machine.scheduled", "Has Work");
        map.put("gate.trigger.redstone.input.active", "Redstone Signal On");
        map.put("gate.trigger.redstone.input.equal", "Redstone Signal Equal");
        map.put("gate.trigger.redstone.input.inactive", "Redstone Signal Off");
        map.put("gate.trigger.redstone.input.greater", "Redstone Signal Greater Than");
        map.put("gate.trigger.redstone.input.less", "Redstone Signal Less Than");
        map.put("gate.trigger.redstone.input.level", "Redstone Level %d");
        map.put("gate.trigger.pipe.empty", "Pipe Empty");
        map.put("gate.trigger.pipe.containsItems", "Items Traversing");
        map.put("gate.trigger.pipe.containsFluids", "Fluid Traversing");
        map.put("gate.trigger.pipe.containsEnergy", "Power Traversing");
        map.put("gate.trigger.pipe.requestsEnergy", "Power Requested");
        map.put("gate.trigger.pipe.tooMuchEnergy", "Power Overloaded");
        map.put("gate.trigger.pipe.wire.active", "%s Pipe Signal On");
        map.put("gate.trigger.pipe.wire.inactive", "%s Pipe Signal Off");
        map.put("gate.trigger.timer", "%s Sec Timer");
        map.put("gate.trigger.robot.sleep", "Sleep");
        map.put("gate.trigger.robot.in.station", "Robot In Station");
        map.put("gate.trigger.robot.linked", "Station Linked");
        map.put("gate.trigger.robot.reserved", "Station Reserved");
        map.put("gate.trigger.machine.energyStored.high", "High Power Stored");
        map.put("gate.trigger.machine.energyStored.low", "Low Power Stored");
        map.put("gate.trigger.machine.energyStored.below25", "Power < 25%");
        map.put("gate.trigger.machine.energyStored.below50", "Power < 50%");
        map.put("gate.trigger.machine.energyStored.below75", "Power < 75%");
        map.put("gate.trigger.light.bright", "Bright");
        map.put("gate.trigger.light.dark", "Dark");
        map.put("gate.trigger.time.0", "Night");
        map.put("gate.trigger.time.6", "Morning");
        map.put("gate.trigger.time.12", "Afternoon");
        map.put("gate.trigger.time.18", "Evening");
        map.put("gate.trigger.fuelLevelBelow", "Fuel level below %d%%");
        map.put("gate.trigger.coolantLevelBelow", "Coolant level below %d%%");
        map.put("gui.fluidtank.empty", "Empty");
        map.put("gui.building.resources", "Building Resources");
        map.put("gui.building.fluids", "Fluid Tanks");
        map.put("gui.del", "Del");
        map.put("gui.filling.resources", "Filling Resources");
        map.put("gui.inventory", "Inventory");
        map.put("gui.lock", "Lock");
        map.put("gui.needed", "Needed");
        map.put("gui.unlock", "Unlock");
        map.put("gui.power", "Power");
        map.put("gui.currentOutput", "Current Output");
        map.put("gui.stored", "Stored");
        map.put("gui.heat", "Heat");
        map.put("gui.assemblyRate", "Rate");
        map.put("gui.assemblyCurrentRequired", "Required");
        map.put("gui.clickcraft", "-Click to Craft-");
        map.put("gui.list.nbt", "Require Exact Match\\n\u00a77(Enchantments, names and stored data must precisely match)");
        map.put("gui.list.metadata", "Accept Variations\\n\u00a77(Same Type)");
        map.put("gui.list.oredict", "Accept Equivalents\\n\u00a77(Same Material)");
        map.put("gui.pipes.emerald.title", "Filters");
        map.put("gui.pipes.emerald.blocking", "Blocking");
        map.put("gui.pipes.emerald.blocking.tip", "Extraction is blocked if one element in filter is missing");
        map.put("gui.pipes.emerald.nonblocking", "Non Blocking");
        map.put("gui.pipes.emerald.nonblocking.tip", "Extraction continues with the next element in filter if one element is missing");
        map.put("gui.pipes.emzuli.title", "Extraction Presets");
        map.put("gui.pipes.emzuli.paint", "Paint Items %s");
        map.put("gui.pipes.emzuli.nopaint", "Don't Paint Items");
        map.put("gui.ledger.ownership", "Owner");
        map.put("gui.ledger.help", "Help");
        map.put("gui.progress", "Progress");
        map.put("gui.leftToBreak", "To break");
        map.put("gui.leftToPlace", "To place");
        map.put("buildcraft.gui.rf_engine.upgrade_types", "Compatible Upgrades:");
        map.put("item.bucketFuel.name", "Fuel Bucket");
        map.put("item.bucketOil.name", "Oil Bucket");
        map.put("item.diamondShard.name", "Diamond Shard");
        map.put("item.woodenGearItem.name", "Wood Gear");
        map.put("item.stoneGearItem.name", "Stone Gear");
        map.put("item.ironGearItem.name", "Iron Gear");
        map.put("item.goldGearItem.name", "Gold Gear");
        map.put("item.diamondGearItem.name", "Diamond Gear");
        map.put("item.templateItem.name", "Template");
        map.put("item.wrenchItem.name", "Wrench");
        map.put("item.paintbrush.name", "Paintbrush");
        map.put("item.pipeWaterproof.name", "Pipe Sealant");
        map.put("item.pipeWire.name", "Pipe Wire");
        map.put("item.redstoneCrystal.name", "Redstone Crystal");
        map.put("item.redstone_red_chipset.name", "Redstone Chipset");
        map.put("item.redstone_iron_chipset.name", "Iron Chipset");
        map.put("item.redstone_gold_chipset.name", "Golden Chipset");
        map.put("item.redstone_diamond_chipset.name", "Diamond Chipset");
        map.put("item.redstone_emerald_chipset.name", "Emerald Chipset");
        map.put("item.redstone_pulsating_chipset.name", "Pulsating Chipset");
        map.put("item.redstone_quartz_chipset.name", "Quartz Chipset");
        map.put("item.redstone_comp_chipset.name", "Redstone Comp Chipset");
        map.put("item.redstone_board.name", "Redstone Board");
        map.put("item.robot.name", "Robot");
        map.put("item.tablet.name", "Tablet");
        map.put("item.blueprintItem.name", "Blueprint");
        map.put("item.schematicSingle.name", "Single Block Schematic");
        map.put("item.list.name", "List");
        map.put("item.blueprint.unnamed", "<unnamed>");
        map.put("item.blueprint.author", "by");
        map.put("item.blueprint.blank", "Blank");
        map.put("item.blueprint.creative_only", "Creative Only");
        map.put("item.blueprint.no_build", "No Building");
        map.put("item.blueprint.incomplete", "Incomplete");
        map.put("item.mapLocation.name", "Map Location");
        map.put("item.gateCopier.name", "Gate Copier");
        map.put("item.plasticSheet.name", "Plastic Sheet");
        map.put("item.markerConnector.name", "Marker Connector");
        map.put("item.pulsar.name", "Pipe Pulsar");
        map.put("item.fragile_fluid_shard.name", "Fragile %s Shard");
        map.put("item.waterGel.name", "Water Gelifier");
        map.put("item.gel.name", "Gelled Water");
        map.put("item.buildcraft_pipe_wood_item.name", "Wooden Transport Pipe");
        map.put("item.buildcraft_pipe_cobblestone_item.name", "Cobblestone Transport Pipe");
        map.put("item.buildcraft_pipe_stone_item.name", "Stone Transport Pipe");
        map.put("item.buildcraft_pipe_andersite_item.name", "Andersite Transport Pipe");
        map.put("item.buildcraft_pipe_andersite_polished_item.name", "Polished Andersite Transport Pipe");
        map.put("item.buildcraft_pipe_diorite_item.name", "Diorite Transport Pipe");
        map.put("item.buildcraft_pipe_diorite_polished_item.name", "Polished Diorite Transport Pipe");
        map.put("item.buildcraft_pipe_granite_item.name", "Granite Transport Pipe");
        map.put("item.buildcraft_pipe_granite_polished_item.name", "Polished Granite Transport Pipe");
        map.put("item.PipeItemsWood.name", "Wooden Transport Pipe");
        map.put("item.PipeItemsCobblestone.name", "Cobblestone Transport Pipe");
        map.put("item.PipeItemsStone.name", "Stone Transport Pipe");
        map.put("item.PipeItemsAndesite.name", "Andesite Transport Pipe");
        map.put("item.PipeItemsDiorite.name", "Diorite Transport Pipe");
        map.put("item.PipeItemsGranite.name", "Granite Transport Pipe");
        map.put("item.PipeItemsQuartz.name", "Quartz Transport Pipe");
        map.put("item.PipeItemsIron.name", "Iron Transport Pipe");
        map.put("item.PipeItemsGold.name", "Golden Transport Pipe");
        map.put("item.PipeItemsDiamond.name", "Diamond Transport Pipe");
        map.put("item.PipeItemsObsidian.name", "Obsidian Transport Pipe");
        map.put("item.PipeItemsWoodenDiamond.name", "Wooden Diamond Transport Pipe");
        map.put("item.PipeItemsLapis.name", "Lazuli Transport Pipe");
        map.put("item.PipeItemsDaizuli.name", "Daizuli Transport Pipe");
        map.put("item.PipeItemsEmzuli.name", "Emzuli Transport Pipe");
        map.put("item.PipeItemsClay.name", "Clay Transport Pipe");
        map.put("item.PipeFluidsWood.name", "Wooden Fluid Pipe");
        map.put("item.PipeFluidsCobblestone.name", "Cobblestone Fluid Pipe");
        map.put("item.PipeFluidsStone.name", "Stone Fluid Pipe");
        map.put("item.PipeFluidsAndesite.name", "Andesite Fluid Pipe");
        map.put("item.PipeFluidsDiorite.name", "Diorite Fluid Pipe");
        map.put("item.PipeFluidsGranite.name", "Granite Fluid Pipe");
        map.put("item.PipeFluidsIron.name", "Iron Fluid Pipe");
        map.put("item.PipeFluidsQuartz.name", "Quartz Fluid Pipe");
        map.put("item.PipeFluidsGold.name", "Golden Fluid Pipe");
        map.put("item.PipeFluidsWoodenDiamond.name", "Wooden Diamond Fluid Pipe");
        map.put("item.PipeFluidsDiamond.name", "Diamond Fluid Pipe");
        map.put("item.PipeFluidsClay.name", "Clay Fluid Pipe");
        map.put("item.PipePowerWood.name", "Wooden Kinesis Pipe");
        map.put("item.PipePowerCobblestone.name", "Cobblestone Kinesis Pipe");
        map.put("item.PipePowerStone.name", "Stone Kinesis Pipe");
        map.put("item.PipePowerQuartz.name", "Quartz Kinesis Pipe");
        map.put("item.PipePowerIron.name", "Iron Kinesis Pipe");
        map.put("item.PipePowerGold.name", "Golden Kinesis Pipe");
        map.put("item.PipePowerDiamond.name", "Diamond Kinesis Pipe");
        map.put("item.PipePowerEmerald.name", "Emerald Kinesis Pipe");
        map.put("item.PipePowerWoodenDiamond.name", "Wooden Diamond Kinesis Pipe");
        map.put("item.PipeRedstoneFluxWood.name", "Wooden Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxCobblestone.name", "Cobblestone Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxStone.name", "Stone Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxQuartz.name", "Quartz Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxIron.name", "Iron Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxGold.name", "Golden Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxDiamond.name", "Diamond Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxEmerald.name", "Emerald Redstone Flux Pipe");
        map.put("item.PipeRedstoneFluxWoodenDiamond.name", "Wooden Diamond Redstone Flux Pipe");
        map.put("item.PipeItemsStripes.name", "Stripes Transport Pipe");
        map.put("item.PipeStructureCobblestone.name", "Cobblestone Structure Pipe");
        map.put("item.PipeItemsVoid.name", "Void Transport Pipe");
        map.put("item.PipeFluidsVoid.name", "Void Fluid Pipe");
        map.put("item.PipeItemsSandstone.name", "Sandstone Transport Pipe");
        map.put("item.PipeFluidsSandstone.name", "Sandstone Fluid Pipe");
        map.put("item.PipePowerSandstone.name", "Sandstone Kinesis Pipe");
        map.put("item.PipeRedstoneFluxSandstone.name", "Sandstone Redstone Flux Pipe");
        map.put("item.PipeRobotStation.name", "Docking Station");
        map.put("item.Facade.name", "Facade");
        map.put("item.Facade.state_hollow", "Hollow");
        map.put("item.FacadePhased.name", "Phased Facade");
        map.put("item.FacadePhased.state", "%s: %s");
        map.put("item.FacadePhased.state_default", "Default: %s");
        map.put("item.FacadePhased.state_transparent", "Transparent");
        map.put("item.PipePlug.name", "Pipe Plug");
        map.put("item.light_sensor.name", "Light Sensor");
        map.put("item.Lens.name", "Lens");
        map.put("item.Filter.name", "Filter");
        map.put("item.timer.name", "Timer");
        map.put("item.PipePowerAdapter.name", "Power Adapter");
        map.put("item.debugger.name", "Debugger");
        map.put("item.debugger.warning", "Use only for testing! Leaks secrets.");
        map.put("item.package.name", "Package");
        map.put("item.buildcraft.guide.name", "BuildCraft Guide Book");
        map.put("item.buildcraft.guide_note.name", "BuildCraft Guide Book Note");
        map.put("item.buildcraft.robot_goggles.name", "Robot Goggles");
        map.put("item.buildcraft.filler_planner.name", "Filler Planner");
        map.put("itemGroup.buildcraft.boards", "BuildCraft Robots");
        map.put("itemGroup.buildcraft.main", "BuildCraft");
        map.put("itemGroup.buildcraft.pipes", "BuildCraft Pipes");
        map.put("itemGroup.buildcraft.facades", "BuildCraft Facades");
        map.put("itemGroup.buildcraft.plugs", "BuildCraft Pluggables");
        map.put("tile.architectBlock.name", "Architect Table");
        map.put("tile.assemblyTableBlock.name", "Assembly Table");
        map.put("tile.assemblyWorkbenchBlock.name", "Advanced Crafting Table");
        map.put("tile.autoWorkbenchBlock.name", "Auto Workbench");
        map.put("tile.blockFuel.name", "Fuel");
        map.put("tile.chuteBlock.name", "Chute");
        map.put("tile.blockOil.name", "Oil");
        map.put("tile.builderBlock.name", "Builder");
        map.put("tile.chargingTableBlock.name", "Charging Table");
        map.put("tile.chargingTableBlock.tip", "Nothing can be charged with this!");
        map.put("tile.constructionMarkerBlock.name", "Construction Mark");
        map.put("tile.engineCreative.name", "Creative Engine");
        map.put("tile.engineCreative.tip", "Right click with a wrench to change power output level.");
        map.put("tile.engineIron.name", "Combustion Engine");
        map.put("tile.engineStone.name", "Stirling Engine");
        map.put("tile.engineWood.name", "Redstone Engine");
        map.put("tile.engineRf.name", "RF Engine");
        map.put("tile.engineRf.tip", "Converts Redstone Flux to Minecraft Joules");
        map.put("tile.mjDynamo.name", "MJ Dynamo");
        map.put("tile.mjDynamo.tip", "Converts Minecraft Joules to Redstone Flux");
        map.put("tile.fillerBlock.name", "Filler");
        map.put("tile.filteredBufferBlock.name", "Filtered Buffer");
        map.put("tile.floodGateBlock.name", "Flood Gate");
        map.put("tile.frameBlock.name", "Frame");
        map.put("tile.integrationTableBlock.name", "Integration Table");
        map.put("tile.laserBlock.name", "Laser");
        map.put("tile.libraryBlock.name", "Electronic Library");
        map.put("tile.quarryBlock.name", "Quarry");
        map.put("tile.markerBlock.name", "Land Mark");
        map.put("tile.miningWellBlock.name", "Mining Well");
        map.put("tile.packagerBlock.name", "Recipe Packager");
        map.put("tile.pathMarkerBlock.name", "Path Mark");
        map.put("tile.plainPipeBlock.name", "Mining Pipe");
        map.put("tile.programmingTableBlock.name", "Programming Table");
        map.put("tile.pumpBlock.name", "Pump");
        map.put("tile.refineryBlock.name", "Refinery");
        map.put("tile.requester.name", "Requester");
        map.put("tile.spring.oil.name", "Oil Spring");
        map.put("tile.spring.water.name", "Water Spring");
        map.put("tile.stampingTableBlock.name", "Stamping Table");
        map.put("tile.tankBlock.name", "Tank");
        map.put("tile.zonePlannerBlock.name", "Zone Planner");
        map.put("tile.distiller.name", "Distiller");
        map.put("tile.heat_exchange.name", "Heat Exchanger");
        map.put("tile.decorated.blueprint.name", "Blueprint (Decoration)");
        map.put("tile.decorated.template.name", "Template (Decoration)");
        map.put("tile.decorated.laser_back.name", "Laser (Decoration)");
        map.put("tile.architect.rotate", "Rotate: On");
        map.put("tile.architect.norotate", "Rotate: Off");
        map.put("tile.architect.allowCreative", "Mode: Creative");
        map.put("tile.architect.noallowCreative", "Mode: Survival");
        map.put("tile.architect.tooltip.allowCreative.1", "Creative allows all blocks - Creative Mode only!");
        map.put("tile.architect.tooltip.allowCreative.2", "Survival ignores all unsupported blocks");
        map.put("tile.architect.excavate", "Excavate: On");
        map.put("tile.architect.noexcavate", "Excavate: Off");
        map.put("tip.gate.wires", "\u00a79\u00a7oCompatible Wires:");
        map.put("tip.gate.wires.redstone", "Red");
        map.put("tip.gate.wires.iron", "Red, Blue");
        map.put("tip.gate.wires.gold", "Red, Blue, Green");
        map.put("tip.gate.wires.quartz", "Red, Blue, Green");
        map.put("tip.gate.wires.diamond", "Red, Blue, Green, Yellow");
        map.put("tip.gate.wires.emerald", "Red, Blue, Green, Yellow");
        map.put("tip.gate.expansions", "\u00a79\u00a7oInstalled Expansions:");
        map.put("tip.PipeFluidsClay", "Insertion pipe");
        map.put("tip.PipeFluidsDiamond", "Sorts fluids");
        map.put("tip.PipeFluidsEmerald", "Extraction pipe");
        map.put("tip.PipeFluidsIron", "Valve pipe");
        map.put("tip.PipeFluidsSandstone", "Only connects to other pipes");
        map.put("tip.PipeFluidsVoid", "Destroys fluids");
        map.put("tip.PipeFluidsWood", "Extraction pipe");
        map.put("tip.PipeItemsClay", "Insertion pipe");
        map.put("tip.PipeItemsDaizuli", "Routes painted items");
        map.put("tip.PipeItemsDiamond", "Sorts items");
        map.put("tip.PipeItemsEmerald", "Round-robin extraction pipe");
        map.put("tip.PipeItemsEmzuli", "Gate controlled extraction pipe");
        map.put("tip.PipeItemsGold", "Speeds up items");
        map.put("tip.PipeItemsIron", "Routes items");
        map.put("tip.PipeItemsLapis", "Paints items");
        map.put("tip.PipeItemsObsidian", "Sucks up items");
        map.put("tip.PipeItemsSandstone", "Only connects to other pipes");
        map.put("tip.PipeItemsVoid", "Destroys items");
        map.put("tip.PipeItemsWood", "Extraction pipe");
        map.put("tip.PipePowerWoodenDiamond", "Power Input Pipe");
        map.put("tip.PipeRedstoneFluxWoodenDiamond", "Redstone Flux Input Pipe");
        map.put("tip.PipePowerIron", "Selectable Limiter Pipe");
        map.put("tip.PipePowerDiamond", "Selectable Limiter Pipe");
        map.put("tip.PipeRedstoneFluxIron", "Selectable Limiter Pipe");
        map.put("tip.PipeRedstoneFluxDiamond", "Selectable Limiter Pipe");
        map.put("tip.PipePowerSandstone", "Only connects to other pipes");
        map.put("tip.PipeRedstoneFluxSandstone", "Only connects to other pipes");
        map.put("tip.PipePowerWood", "Power Input Pipe");
        map.put("tip.PipeStructureCobblestone", "Support pipe");
        map.put("tip.deprecated", "Deprecated");
        map.put("tip.gate.charged", "Charged");
        map.put("tip.gate.fullcharge", "Full Charge");
        map.put("tip.gate.nocharge", "No Charge");
        map.put("tip.filler.excavate.on", "Excavate");
        map.put("tip.filler.excavate.off", "Do Not Excavate");
        map.put("tip.filler.invert.on", "Invert");
        map.put("tip.filler.invert.off", "Do Not Invert");
        map.put("tip.list.matches", "Matches");
        map.put("tip.shift.PipeFluidsDiamond", "GUI accepts any fluid containers");
        map.put("tip.shift.PipeFluidsEmerald", "GUI accepts any fluid container");
        map.put("tip.shift.PipeItemsClay", "Prioritizes machines and chests\\nover neighbouring pipes.");
        map.put("tip.shift.PipeItemsDaizuli", "Sneak-click to change color");
        map.put("tip.shift.PipeItemsEmzuli", "Set extraction preset filters in GUI\\nA preset can paint extracted items\\nSwitch extraction presets via gates");
        map.put("tip.shift.PipeItemsLapis", "Sneak-click to change color");
        map.put("tip.shift.PipeItemsObsidian", "Power with an engine\\nMore power - greater distance");
        map.put("tip.shift.PipePowerDiamond", "Change the limit with a wrench or gates");
        map.put("tip.PipeItemsEmerald.whitelist", "Whitelist");
        map.put("tip.PipeItemsEmerald.blacklist", "Blacklist");
        map.put("tip.PipeItemsEmerald.roundrobin", "Round Robin (In Order)");
        map.put("tip.tool.add", "Add");
        map.put("tip.tool.fullscreen", "Fullscreen");
        map.put("tip.tool.remove", "Remove");
        map.put("achievement.woodenGearAchievement", "A bit rough around the edges");
        map.put("achievement.woodenGearAchievement.desc", "Craft a wooden gear");
        map.put("achievement.stoneGearAchievement", "Hard as a rock");
        map.put("achievement.stoneGearAchievement.desc", "Upgrade a wooden gear to a stone gear");
        map.put("achievement.ironGearAchievement", "Is it stainless?");
        map.put("achievement.ironGearAchievement.desc", "Upgrade a stone gear to an iron gear");
        map.put("achievement.goldGearAchievement", "No, it isn't made of honey");
        map.put("achievement.goldGearAchievement.desc", "Upgrade an iron gear to a gold gear");
        map.put("achievement.diamondGearAchievement", "Shiny!");
        map.put("achievement.diamondGearAchievement.desc", "Upgrade a gold gear to a diamond gear");
        map.put("achievement.wrenchAchievement", "Just hit it!");
        map.put("achievement.wrenchAchievement.desc", "Make a wrench");
        map.put("achievement.engineAchievement1", "The start of something big");
        map.put("achievement.engineAchievement1.desc", "Craft a redstone engine");
        map.put("achievement.engineAchievement2", "High efficiency");
        map.put("achievement.engineAchievement2.desc", "Craft a stirling engine");
        map.put("achievement.engineAchievement3", "Powerhouse");
        map.put("achievement.engineAchievement3.desc", "Craft a combustion engine");
        map.put("achievement.aLotOfCraftingAchievement", "A lot of crafting");
        map.put("achievement.aLotOfCraftingAchievement.desc", "Craft an auto workbench");
        map.put("achievement.straightDownAchievement", "Straight down");
        map.put("achievement.straightDownAchievement.desc", "Make a mining well");
        map.put("achievement.chunkDestroyerAchievement", "Chunk destroyer");
        map.put("achievement.chunkDestroyerAchievement.desc", "Craft a quarry");
        map.put("achievement.fasterFillingAchievement", "Faster filling");
        map.put("achievement.fasterFillingAchievement.desc", "Make a filler");
        map.put("achievement.timeForSomeLogicAchievement", "Time for some logic");
        map.put("achievement.timeForSomeLogicAchievement.desc", "Craft an assembly table");
        map.put("achievement.refineAndRedefineAchievement", "Refine and redefine");
        map.put("achievement.refineAndRedefineAchievement.desc", "Make a refinery");
        map.put("achievement.tinglyLaserAchievement", "Tingly laser");
        map.put("achievement.tinglyLaserAchievement.desc", "Craft a laser");
        map.put("achievement.architectAchievement", "Architecture");
        map.put("achievement.architectAchievement.desc", "Craft an architect table");
        map.put("achievement.builderAchievement", "I've got better things to do");
        map.put("achievement.builderAchievement.desc", "Craft a builder");
        map.put("achievement.blueprintAchievement", "Building reference");
        map.put("achievement.blueprintAchievement.desc", "Craft a blueprint");
        map.put("achievement.templateAchievement", "Basis");
        map.put("achievement.templateAchievement.desc", "Craft a template");
        map.put("achievement.blueprintLibraryAchievement", "Ideas live on");
        map.put("achievement.blueprintLibraryAchievement.desc", "Craft an electronic library");
        map.put("bc_update.new_version", "\u00a7cNew version of BuildCraft available: %s for Minecraft %s");
        map.put("bc_update.download", "\u00a7cDownload from http://www.mod-buildcraft.com/download");
        map.put("bc_update.once", "This message only displays once");
        map.put("bc_update.again", "Type '/buildcraft version' if you want to see it again");
        map.put("bc_update.changelog", "Type '/buildcraft changelog' to see the changelog");
        map.put("chat.buildcraft.quarry.tooSmall", "[BuildCraft] Quarry size is outside of chunkloading bounds or too small %d %d (%d)");
        map.put("chat.buildcraft.quarry.chunkloadInfo", "[BuildCraft] The quarry at %d %d %d will keep %d chunks loaded");
        map.put("command.buildcraft.version", "BuildCraft %s for Minecraft %s (Latest: %s).");
        map.put("command.buildcraft.changelog_header", "Changelog for BuildCraft %s:");
        map.put("command.buildcraft.version.fail", "Version check failed! Check the log file for details.");
        map.put("command.buildcraft.version.prerelease", "You are using a pre-release build");
        map.put("command.buildcraft.aliases", "Aliases: %s");
        map.put("command.buildcraft.help", "Type '%s' for help.");
        map.put("command.buildcraft.list", "Available Commands:");
        map.put("command.buildcraft.permlevel", "Permission level: %s");
        map.put("command.buildcraft.noperms", "You do not have permission to use this command.");
        map.put("command.buildcraft.buildcraft.help", "Various BuildCraft-related commands");
        map.put("command.buildcraft.buildcraft.format", "Format: /%s <sub-command>");
        map.put("command.buildcraft.buildcraft.version.desc", "- %s : Version Information");
        map.put("command.buildcraft.buildcraft.version.help", "Displays the current and latest BC version.");
        map.put("command.buildcraft.buildcraft.version.format", "Format: /%s");
        map.put("command.buildcraft.buildcraft.changelog.desc", "- %s : Changelog");
        map.put("command.buildcraft.buildcraft.changelog.help", "Displays the latest BC changelog.");
        map.put("command.buildcraft.buildcraft.changelog.format", "Format: /%s");
        map.put("buildcraft.item.nonclean.usage", "Shift-right click to clean");
        map.put("buildcraft.guide.book.meta.name", "BuildCraft Configuration Guide");
        map.put("buildcraft.guide_book.reloaded", "Guide Book Reloaded");
        map.put("buildcraft.guide.too_many_results", "Too many results to display: %s");
        map.put("buildcraft.guide.chapter_list", "Chapters");
        map.put("buildcraft.guide.contents.loaded_modules", "Loaded modules:");
        map.put("buildcraft.guide.contents.missing_modules", "Missing modules:");
        map.put("buildcraft.guide.order.type_subtype", "Sort By Type");
        map.put("buildcraft.guide.order.mod_type", "Sort By Mod");
        map.put("buildcraft.guide.order.alphabetical", "Sort Alphabetically");
        map.put("buildcraft.guide.recipe.create", "Recipe");
        map.put("buildcraft.guide.recipe.create.plural", "Recipes");
        map.put("buildcraft.guide.recipe.use", "Use");
        map.put("buildcraft.guide.recipe.use.plural", "Uses");
        map.put("buildcraft.guide.chapter.contents", "Contents");
        map.put("buildcraft.guide.contents.all_group", "Others");
        map.put("buildcraft.guide.contents.item_stacks", "Items and Blocks");
        map.put("buildcraft.guide.contents.triggers", "Triggers");
        map.put("buildcraft.guide.contents.actions", "Actions");
        map.put("buildcraft.guide.chapter.type.unknown", "Unknown Type!");
        map.put("buildcraft.guide.chapter.subtype.unknown", "Unknown Subtype!");
        map.put("buildcraft.guide.chapter.mod.unknown", "Unknown Mod!");
        map.put("buildcraft.guide.chapter.submod.unknown", "Unknown SubMod!");
        map.put("buildcraft.guide.meta.group.linking_to", "Linked To");
        map.put("buildcraft.guide.meta.group.linked_from", "Linked From");
        map.put("buildcraft.guide.group.to.buildcraft.pipe_power_providers", "Pipe Power Providers");
        map.put("buildcraft.guide.group.from.buildcraft.pipe_power_providers", "Pipe Power Receivers");
        map.put("buildcraft.guide.group.to.buildcraft.full_power_providers", "Full Power Providers");
        map.put("buildcraft.guide.group.from.buildcraft.full_power_providers", "Full Power Receivers");
        map.put("buildcraft.guide.group.to.buildcraft.laser_power_providers", "Laser Power Providers");
        map.put("buildcraft.guide.group.from.buildcraft.laser_power_providers", "Laser Power Receivers");
        map.put("buildcraft.guide.group.to.buildcraft.area_markers", "Area Markers");
        map.put("buildcraft.guide.group.from.buildcraft.area_markers", "Area dependent blocks");
        map.put("buildcraft.help.tank.generic", "Clicking this with an empty bucket will\\nempty this tank into the bucket, or\\nusing a full bucket will fill this tank\\nfrom the bucket.");
        map.put("buildcraft.help.tank.title.tankFuel", "Fuel Tank");
        map.put("buildcraft.help.tank.title.tankCoolant", "Coolant Tank");
        map.put("buildcraft.help.tank.title.tankResidue", "Residue Tank");
        map.put("buildcraft.help.tank.fuel", "This tank can accept any kind of fuel.");
        map.put("buildcraft.help.tank.coolant", "This tank can accept any kind of fluid\\ncoolant, or ice blocks.");
        map.put("buildcraft.help.tank.residue", "This tank will output residue if the\\nfuel hasn't been processed\\n(for example oil).");
        map.put("buildcraft.help.stone_engine.flame.title", "Fuel left");
        map.put("buildcraft.help.stone_engine.fuel.title", "Fuel input");
        map.put("buildcraft.help.stone_engine.flame", "THIS BURNS AND THIS HELP ISN'T DONE YET.");
        map.put("buildcraft.help.stone_engine.fuel", "Accepts any fuel that a furnace does.");
        map.put("buildcraft.help.rf_engine.upgrades.title", "Upgrades");
        map.put("buildcraft.help.rf_engine.upgrades.desc", "Add compatible gears to\\nincrease conversion rate.\\n\\nMax 1 gear per slot.");
        map.put("buildcraft.help.rf_engine.rf_battery.title", "RF Battery");
        map.put("buildcraft.help.rf_engine.rf_battery.desc", "Converts %s\\nto %s");
        map.put("buildcraft.help.mj_dynamo.rf_battery.title", "RF Battery");
        map.put("buildcraft.help.mj_dynamo.rf_battery.desc", "Converts %s\\nto %s");
        map.put("command.buildcraft.buildcraft.op.desc", "- %s : Op FakePlayer");
        map.put("command.buildcraft.buildcraft.op.help", "Gives OP rights to the BC FakePlayer (acts in the name of quarries, robots, etc.)");
        map.put("command.buildcraft.buildcraft.op.format", "Format: /%s");
        map.put("command.buildcraft.buildcraft.deop.desc", "- %s : Deop FakePlayer");
        map.put("command.buildcraft.buildcraft.deop.help", "Ungives OP rights to the BC FakePlayer (acts in the name of quarries, robots, etc.)");
        map.put("command.buildcraft.buildcraft.deop.format", "Format: /%s");
        map.put("advancements.buildcraftcore.root.title", "BuildCraft");
        map.put("advancements.buildcraftcore.root.description", "For all your engineering needs");
        map.put("advancements.buildcraftcore.guide.title", "How does this work again?");
        map.put("advancements.buildcraftcore.guide.description", "Check out the guide");
        map.put("advancements.buildcraftcore.gears.title", "Gearing up");
        map.put("advancements.buildcraftcore.gears.description", "Get one of each gear");
        map.put("advancements.buildcraftcore.wrenched.title", "Wrenched!");
        map.put("advancements.buildcraftcore.wrenched.description", "Use the wrench");
        map.put("advancements.buildcraftcore.freePowar.title", "Free Power!");
        map.put("advancements.buildcraftcore.freePowar.description", "Generate free power");
        map.put("advancements.buildcraftcore.list.title", "Sorting all the things");
        map.put("advancements.buildcraftcore.list.description", "Discover the advanced capabilities of the list");
        map.put("advancements.buildcraftcore.engine.title", "My first engine");
        map.put("advancements.buildcraftcore.engine.description", "Get your first engine");
        map.put("advancements.buildcraftcore.markers.title", "Marking your territory");
        map.put("advancements.buildcraftcore.markers.description", "Use volume markers to mark out an area");
        map.put("advancements.buildcraftcore.path_markers.title", "Defining the trail");
        map.put("advancements.buildcraftcore.path_markers.description", "Define a path");
        map.put("advancements.buildcraftcore.paper.title", "Paper collector");
        map.put("advancements.buildcraftcore.paper.description", "Use every piece of paper");
        map.put("advancements.buildcraftenergy.poweringUp.title", "Powering Up!");
        map.put("advancements.buildcraftenergy.poweringUp.description", "Activate a Stirling/Combustion engine with a redstone signal");
        map.put("advancements.buildcraftenergy.lava_power.title", "Lava Power");
        map.put("advancements.buildcraftenergy.lava_power.description", "Power a stirling engine with a lava bucket");
        map.put("advancements.buildcraftenergy.to_much_power.title", "To much power!");
        map.put("advancements.buildcraftenergy.to_much_power.description", "Make an engine overheat and wackit it with a wrench");
        map.put("advancements.buildcraftenergy.ice_cool.title", "Ice cool");
        map.put("advancements.buildcraftenergy.ice_cool.description", "Cool a combustion engine with something else then water (if available)");
        map.put("advancements.buildcraftenergy.sticky_dipping.title", "Sticky dipping");
        map.put("advancements.buildcraftenergy.sticky_dipping.description", "Discover the sticky nature of oil");
        map.put("advancements.buildcraftenergy.fine_riches.title", "Fine riches");
        map.put("advancements.buildcraftenergy.fine_riches.description", "Find an oil biome");
        map.put("advancements.buildcraftenergy.refine_and_redefine.title", "Refine and redefine");
        map.put("advancements.buildcraftenergy.refine_and_redefine.description", "Produce a tank full of every single type of oil and fuel");
        map.put("advancements.buildcraftfactory.fluid_storage.title", "Fluid storage");
        map.put("advancements.buildcraftfactory.fluid_storage.description", "Store fluid in a tank");
        map.put("advancements.buildcraftfactory.lazy_crafting.title", "Lazy crafting");
        map.put("advancements.buildcraftfactory.lazy_crafting.description", "Make the autoworkbench work for you");
        map.put("advancements.buildcraftfactory.retired_hopper.title", "Retired hopper");
        map.put("advancements.buildcraftfactory.retired_hopper.description", "Put the chute back to work");
        map.put("advancements.buildcraftfactory.flooding_the_world.title", "Flooding the world");
        map.put("advancements.buildcraftfactory.flooding_the_world.description", "Flood the area with a floodgate");
        map.put("advancements.buildcraftfactory.draining_the_world.title", "Draining the world");
        map.put("advancements.buildcraftfactory.draining_the_world.description", "Use a pump to drain fluids from the world");
        map.put("advancements.buildcraftfactory.oil_platform.title", "Oil platform");
        map.put("advancements.buildcraftfactory.oil_platform.description", "Start Pumping up an oil spout");
        map.put("advancements.buildcraftfactory.heating_and_distilling.title", "Heating and Distilling");
        map.put("advancements.buildcraftfactory.heating_and_distilling.description", "Create a complete oil refining setup with a Distiller and a Heat Exchanger");
        map.put("advancements.buildcraftfactory.black_gold.title", "Black gold");
        map.put("advancements.buildcraftfactory.black_gold.description", "Completely pump out a large oil spout");
        map.put("advancements.buildcraftsilicon.laser_power.title", "Laser power");
        map.put("advancements.buildcraftsilicon.laser_power.description", "Make a laser");
        map.put("advancements.buildcraftsilicon.precision_crafting.title", "Precision crafting");
        map.put("advancements.buildcraftsilicon.precision_crafting.description", "Start crafting with an assembly table");
        map.put("advancements.buildcrafttransport.pipe_dream.title", "Pipe dream");
        map.put("advancements.buildcrafttransport.pipe_dream.description", "Place a pipe");
        map.put("advancements.buildcrafttransport.pipe_diversification.title", "Pipe diversification");
        map.put("advancements.buildcrafttransport.pipe_diversification.description", "Place a item, fluid, kinesis and structure pipe");
        map.put("advancements.buildcrafttransport.plugging_the_gap.title", "Plugging the gap");
        map.put("advancements.buildcrafttransport.plugging_the_gap.description", "Plug a pipe");
        map.put("advancements.buildcrafttransport.logic_transportation.title", "Logic transportation");
        map.put("advancements.buildcrafttransport.logic_transportation.description", "Connect pipe wires");
        map.put("advancements.buildcrafttransport.extended_logic.title", "Extended logic");
        map.put("advancements.buildcrafttransport.extended_logic.description", "Use a gate with extra slots");
        map.put("advancements.buildcrafttransport.sealing_fluids.title", "Sealing fluids");
        map.put("advancements.buildcrafttransport.sealing_fluids.description", "Smelt a cactus and craft it's dye to produce pipe sealant");
        map.put("advancements.buildcrafttransport.pipe_logic.title", "Pipe logic");
        map.put("advancements.buildcrafttransport.pipe_logic.description", "Place a gate on a pipe");
        map.put("advancements.buildcrafttransport.all_plugged_up.title", "All plugged up");
        map.put("advancements.buildcrafttransport.all_plugged_up.description", "Attach one of each unique pluggable to a pipe");
        map.put("advancements.buildcrafttransport.pipe_fanatic.title", "Pipe fanatic");
        map.put("advancements.buildcrafttransport.pipe_fanatic.description", "Place down one of each type of pipe");
        map.put("advancements.buildcrafttransport.categorizing_with_colors.title", "Categorizing with colors");
        map.put("advancements.buildcrafttransport.categorizing_with_colors.description", "Setup a sorting setup using the power of colouring");
        map.put("advancements.buildcrafttransport.colorful_electrician.title", "Colorful electrician");
        map.put("advancements.buildcrafttransport.colorful_electrician.description", "Use 16 of each color of pipe wire to make your piping system more robust");
        map.put("advancements.buildcraftbuilders.shaping_the_world.title", "Shaping the world");
        map.put("advancements.buildcraftbuilders.shaping_the_world.description", "Craft and place a Quarry");
        map.put("advancements.buildcraftbuilders.architect.title", "Architect");
        map.put("advancements.buildcraftbuilders.architect.description", "Scan an area with an architect table and record it in a blueprint/template");
        map.put("advancements.buildcraftbuilders.paving_the_way.title", "Paving the way");
        map.put("advancements.buildcraftbuilders.paving_the_way.description", "Utilize the builder with a pathmarker to create a path");
        map.put("advancements.buildcraftbuilders.diggy.title", "Diggy diggy hole");
        map.put("advancements.buildcraftbuilders.diggy.description", "Have a 64x64 quarry finish");
        map.put("advancements.buildcraftbuilders.start_of_something_big.title", "Start of something big");
        map.put("advancements.buildcraftbuilders.start_of_something_big.description", "Build an extra-large structure with the builder");
        map.put("advancements.buildcraftbuilders.building_for_the_future.title", "Building for the future");
        map.put("advancements.buildcraftbuilders.building_for_the_future.description", "Set a filler on a loop for long term automation");
        map.put("advancements.buildcraftbuilders.destroying_the_world.title", "Destorying the world");
        map.put("advancements.buildcraftbuilders.destroying_the_world.description", "Have two or more 64 x 64 sized quarries running at once at full speed");
        map.put("advancements.buildcrafttransport.too_many_pipe_filters.title", "Too many filters");
        map.put("advancements.buildcrafttransport.too_many_pipe_filters.description", "Try using a list");
        map.put("tile.replacerBlock.name", "Replacer");
        map.put("tile.waterGel.name", "Water Gelifier");
        map.put("tile.tubeBlock.name", "Tube");
        map.put("tile.power_tester.name", "Power Tester");
        map.put("item.globOil.name", "Oil Glob [How did you get this?!]");
        map.put("item.oilPlacer.name", "\u00a7e[Debug Tool] \u00a7bOil Well Placer");
        map.put("item.volume_box.name", "Volume Box");
        map.put("item.buildcraft.bucket_filled", "%s Bucket");
        map.put("gui.creativetab.pipe.button.all", "All Colours");
        map.put("gui.creativetab.pipe.button.filtered", "Only %s");
        map.put("item.minecraft.firework_star.colorless", "\u00a7fColorless");
        map.put("chat.buildcraft.schematic_single.not_enough_item", "Not enough items. Total needed: ");
        map.put("chat.buildcraft.schematic_single.require_fluid", "Schematic requires fluids");
        map.put("chat.buildcraft.schematic_single.invalid", "Invalid schematic: ");
        map.put("buildcraft.help.tank.title.tank1", "Tank 1");
        map.put("buildcraft.help.tank.title.tank2", "Tank 2");
        map.put("buildcraft.help.tank.title.tank3", "Tank 3");
        map.put("buildcraft.help.tank.title.tank4", "Tank 4");
        map.put("buildcraft.param.facing.north", "Facing north");
        map.put("buildcraft.param.facing.west", "Facing west");
        map.put("buildcraft.param.facing.east", "Facing east");
        map.put("buildcraft.param.facing.south", "Facing south");
        map.put("buildcraft.param.facing.up", "Facing up");
        map.put("buildcraft.param.facing.down", "Facing down");
        map.put("null", "=w=");
    }
}
